# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.import_data = QtWidgets.QWidget()
        self.import_data.setObjectName("import_data")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.import_data)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.features_label = QtWidgets.QLabel(self.import_data)
        self.features_label.setObjectName("features_label")
        self.gridLayout_2.addWidget(self.features_label, 3, 2, 1, 1)
        self.log_label = QtWidgets.QLabel(self.import_data)
        self.log_label.setObjectName("log_label")
        self.gridLayout_2.addWidget(self.log_label, 2, 2, 1, 1)
        self.log_button = QtWidgets.QPushButton(self.import_data)
        self.log_button.setObjectName("log_button")
        self.gridLayout_2.addWidget(self.log_button, 2, 4, 1, 1)
        self.features_button = QtWidgets.QPushButton(self.import_data)
        self.features_button.setObjectName("features_button")
        self.gridLayout_2.addWidget(self.features_button, 3, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 5, 1, 1)
        self.read_button = QtWidgets.QPushButton(self.import_data)
        self.read_button.setObjectName("read_button")
        self.gridLayout_2.addWidget(self.read_button, 4, 2, 1, 3)
        self.data_table = QtWidgets.QTableView(self.import_data)
        self.data_table.setObjectName("data_table")
        self.gridLayout_2.addWidget(self.data_table, 0, 0, 1, 6)
        self.tabWidget.addTab(self.import_data, "")
        self.search_data = QtWidgets.QWidget()
        self.search_data.setObjectName("search_data")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.search_data)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.search_button = QtWidgets.QPushButton(self.search_data)
        self.search_button.setObjectName("search_button")
        self.gridLayout_3.addWidget(self.search_button, 4, 0, 1, 1)
        self.search_result_label = QtWidgets.QLabel(self.search_data)
        self.search_result_label.setObjectName("search_result_label")
        self.gridLayout_3.addWidget(self.search_result_label, 2, 0, 1, 1)
        self.search_table = QtWidgets.QTableView(self.search_data)
        self.search_table.setLineWidth(1)
        self.search_table.setMidLineWidth(0)
        self.search_table.setObjectName("search_table")
        self.gridLayout_3.addWidget(self.search_table, 0, 0, 1, 1)
        self.export_results_button = QtWidgets.QPushButton(self.search_data)
        self.export_results_button.setObjectName("export_results_button")
        self.gridLayout_3.addWidget(self.export_results_button, 1, 0, 1, 1)
        self.search_textedit = QtWidgets.QLineEdit(self.search_data)
        self.search_textedit.setObjectName("search_textedit")
        self.gridLayout_3.addWidget(self.search_textedit, 3, 0, 1, 1)
        self.tabWidget.addTab(self.search_data, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.export_stats_button = QtWidgets.QAction(MainWindow)
        self.export_stats_button.setObjectName("export_stats_button")
        self.menuOptions.addAction(self.export_stats_button)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GOTCHA"))
        self.features_label.setText(_translate("MainWindow", "No features file selected."))
        self.log_label.setText(_translate("MainWindow", "No log file selected."))
        self.log_button.setText(_translate("MainWindow", "Select Log File"))
        self.features_button.setText(_translate("MainWindow", "Select Features File"))
        self.read_button.setText(_translate("MainWindow", "Read Log File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.import_data), _translate("MainWindow", "Import Data"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.search_result_label.setText(_translate("MainWindow", "Search Result Remarks: None"))
        self.export_results_button.setText(_translate("MainWindow", "Export Results"))
        self.search_textedit.setPlaceholderText(_translate("MainWindow", "Enter Search Term. Press \'Search\' without entering anything to view entire data set."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search_data), _translate("MainWindow", "Search Data"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.export_stats_button.setText(_translate("MainWindow", "Export Statistics"))
